// lcc: exhaustive Length-Capped Component search in the official rank-2 AC move graph (ac-r2-v1).
//
// Graph G_L: vertices = ordered pairs (r0, r1) of nonempty freely reduced words over {x,X,y,Y} with
// |r0| + |r1| <= L; edges = the 14 official moves (ids 0-13, inversion-closed, so G_L is undirected)
// whenever both endpoints lie in G_L.  (Empty relators never occur in a component of a presentation of
// the trivial group, since <x,y | r> is never trivial; so excluding them loses nothing.)
//
// lcc computes the connected component C_L(S) of a start state S in G_L by BFS and reports
//   * its size per BFS layer,
//   * whether it contains the standard presentation (x, y)  [TRIVIAL] or not [NOT-TRIVIAL],
//   * which states from a watch list lie in C_L(S), with their BFS distance.
//
// Mode --quot: BFS in the quotient of G_L by the 16-element group Sigma generated by the 8 signed
// permutations of {x, y} (letter automorphisms of F2) and the swap (r0, r1) -> (r1, r0).  Each element
// of Sigma is a length-preserving graph automorphism of G_L (it permutes move ids), and for L >= 4 the
// component of (x, y) is Sigma-invariant (all 8 signed permutations of (x,y) are joined to (x,y) by
// short paths of total length <= 4, see README).  Hence (x, y) is in C_L(S) iff the Sigma-orbit of
// (x, y) meets the quotient component of [S].  Watch-list hits in --quot mode only certify
// "X ~ sigma(Y) for some sigma in Sigma".  With --paths, each hit Y gets an explicit move sequence from S to
// sigma(Y) (sigma = 0 means the identity, always so in exact mode); sigma = 8*swap + 4*[x<->y] + 2*[x->x^-1] + [y->y^-1]
// in the letter-map encoding of init_sym (see scripts/replay.py, which re-derives it independently).
//
//   lcc --cap L [--full] [--quot] [--log2 K] [--watch FILE] [--paths OUT] [--dump OUT] [--threads T] -- r0 | r1
//
// --full: do not stop when (x,y) is reached (exhaust the component anyway; used for validation).
// State words on the command line use 1=x -1=x^-1 2=y -2=y^-1.  --paths writes, for every watch hit,
// a move sequence (ids 0-13) from S to the hit (exact mode only), for independent replay.
// --dump writes the sorted packed keys of the component (certificate for scripts/check_closure).
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
using namespace std;

constexpr int MAXL = 27;
struct St { uint8_t n0 = 0, n1 = 0; uint8_t c[MAXL + 4]; int tot() const { return n0 + n1; } };

static inline int inv_word(const uint8_t* a, int n, uint8_t* out) { for (int i = 0; i < n; i++) out[i] = a[n - 1 - i] ^ 1; return n; }
static inline int concat(const uint8_t* a, int na, const uint8_t* b, int nb, uint8_t* out) {
    int i = na, j = 0;
    while (i > 0 && j < nb && (a[i - 1] ^ 1) == b[j]) i--, j++;
    memcpy(out, a, i); memcpy(out + i, b + j, nb - j);
    return i + nb - j;
}
static inline int conj(const uint8_t* w, int n, int c, uint8_t* out) {  // c w c^-1 freely reduced
    int k;
    if (w[0] == (c ^ 1)) { memcpy(out, w + 1, n - 1); k = n - 1; }
    else { out[0] = c; memcpy(out + 1, w, n); k = n + 1; }
    if (k && out[k - 1] == c) return k - 1;
    out[k] = c ^ 1; return k + 1;
}
// Letters 0=x 1=X 2=y 3=Y. Move ids as in the official ac-r2-v1 table.
static bool apply(const St& s, int m, St& o, int cap) {
    uint8_t w[2 * MAXL + 8], t[MAXL + 4];
    const uint8_t *r0 = s.c, *r1 = s.c + s.n0; int a = s.n0, b = s.n1, n;
    bool first = (m == 0 || m == 2 || m == 3 || (m >= 6 && m <= 9));
    switch (m) {
        case 0: n = inv_word(r0, a, w); break;
        case 1: n = inv_word(r1, b, w); break;
        case 2: n = concat(r0, a, r1, b, w); break;
        case 3: inv_word(r1, b, t); n = concat(r0, a, t, b, w); break;
        case 4: n = concat(r1, b, r0, a, w); break;
        case 5: inv_word(r0, a, t); n = concat(r1, b, t, a, w); break;
        default: n = m < 10 ? conj(r0, a, m - 6, w) : conj(r1, b, m - 10, w);
    }
    if (n <= 0) return false;
    int other = first ? b : a;
    if (n + other > cap) return false;
    if (first) { o.n0 = n; o.n1 = b; memcpy(o.c, w, n); memcpy(o.c + n, r1, b); }
    else { o.n0 = a; o.n1 = n; memcpy(o.c, r0, a); memcpy(o.c + a, w, n); }
    return true;
}
static inline uint64_t pack(const St& s) {
    uint64_t k = s.n0 | (uint64_t)s.n1 << 5;
    for (int i = 0; i < s.tot(); i++) k |= (uint64_t)s.c[i] << (10 + 2 * i);
    return k;
}
static inline St unpack(uint64_t k) {
    St s; s.n0 = k & 31; s.n1 = (k >> 5) & 31;
    for (int i = 0; i < s.tot(); i++) s.c[i] = (k >> (10 + 2 * i)) & 3;
    return s;
}
// Sigma: 8 letter maps x 2 (swap). LET[g][l] = image of letter l.
static uint8_t LET[8][4];
static void init_sym() {
    int g = 0;
    for (int sw = 0; sw < 2; sw++) for (int sx = 0; sx < 2; sx++) for (int sy = 0; sy < 2; sy++, g++) {
        int X = sw ? 2 : 0, Y = sw ? 0 : 2;       // image generator of x and y
        LET[g][0] = X | sx; LET[g][1] = X | (sx ^ 1);
        LET[g][2] = Y | sy; LET[g][3] = Y | (sy ^ 1);
    }
}
static inline St sym(const St& s, int g) {  // g in 0..15: g&7 letter map, g>>3 swap relators
    St o; const uint8_t* L = LET[g & 7];
    if (g >> 3) { o.n0 = s.n1; o.n1 = s.n0; for (int i = 0; i < s.n1; i++) o.c[i] = L[s.c[s.n0 + i]]; for (int i = 0; i < s.n0; i++) o.c[s.n1 + i] = L[s.c[i]]; }
    else { o.n0 = s.n0; o.n1 = s.n1; for (int i = 0; i < s.tot(); i++) o.c[i] = L[s.c[i]]; }
    return o;
}
static bool QUOT = false;
static inline uint64_t key(const St& s) {
    if (!QUOT) return pack(s);
    uint64_t best = ~0ULL;
    for (int g = 0; g < 16; g++) best = min(best, pack(sym(s, g)));
    return best;
}
static inline uint64_t mix(uint64_t x) { x ^= x >> 30; x *= 0xbf58476d1ce4e5b9ULL; x ^= x >> 27; x *= 0x94d049bb133111ebULL; return x ^ (x >> 31); }

// Lock-free open-addressing set (keys never 0: n0 >= 1 always, so pack() != 0) with a BFS layer byte.
struct Table {
    vector<atomic<uint64_t>> k; vector<uint8_t> d; uint64_t mask; atomic<uint64_t> n{0};
    explicit Table(int lg) : k(1ULL << lg), d(1ULL << lg, 255), mask((1ULL << lg) - 1) { for (auto& x : k) x.store(0, memory_order_relaxed); }
    bool insert(uint64_t key, uint8_t dist) {
        uint64_t i = mix(key) & mask;
        for (;;) {
            uint64_t cur = k[i].load(memory_order_relaxed);
            if (cur == key) return false;
            if (cur == 0) {
                uint64_t z = 0;
                if (k[i].compare_exchange_strong(z, key)) { d[i] = dist; n++; return true; }
                if (z == key) return false;
                continue;
            }
            i = (i + 1) & mask;
        }
    }
    int get(uint64_t key) const {
        uint64_t i = mix(key) & mask;
        for (;;) { uint64_t cur = k[i].load(memory_order_relaxed); if (cur == key) return d[i]; if (!cur) return -1; i = (i + 1) & mask; }
    }
};

static St parse(const vector<int>& a, const vector<int>& b) {
    St s; s.n0 = a.size(); s.n1 = b.size();
    for (size_t i = 0; i < a.size(); i++) s.c[i] = (abs(a[i]) - 1) * 2 + (a[i] < 0);
    for (size_t i = 0; i < b.size(); i++) s.c[a.size() + i] = (abs(b[i]) - 1) * 2 + (b[i] < 0);
    return s;
}
static string show(const St& s) {
    string o; const char* L = "xXyY";
    for (int i = 0; i < s.tot(); i++) { if (i == s.n0) o += " | "; o += L[s.c[i]]; }
    return o;
}
static bool parse_line(const string& line, string& id, St& s) {  // "id a b c | d e f"
    char buf[64]; int off = 0;
    if (sscanf(line.c_str(), "%63s%n", buf, &off) != 1 || buf[0] == '#') return false;
    id = buf; vector<int> a, b; bool second = false; const char* p = line.c_str() + off;
    while (*p) {
        while (*p == ' ' || *p == '\t') p++;
        if (!*p || *p == '#' || *p == '\n') break;
        if (*p == '|') { second = true; p++; continue; }
        char* e; long v = strtol(p, &e, 10); if (e == p) break; p = e;
        (second ? b : a).push_back((int)v);
    }
    if (a.empty() || b.empty() || a.size() + b.size() > MAXL) return false;
    s = parse(a, b); return true;
}

#ifndef LCC_NO_MAIN
int main(int argc, char** argv) {
    init_sym();
    int cap = 0, lg = 24, threads = 1; string watch, paths, dump; vector<int> a, b; bool second = false, words = false, full = false;
    for (int i = 1; i < argc; i++) {
        string t = argv[i];
        if (words) { if (t == "|") second = true; else (second ? b : a).push_back(atoi(argv[i])); continue; }
        if (t == "--cap") cap = atoi(argv[++i]);
        else if (t == "--quot") QUOT = true;
        else if (t == "--full") full = true;
        else if (t == "--log2") lg = atoi(argv[++i]);
        else if (t == "--threads") threads = max(1, min(2, atoi(argv[++i])));
        else if (t == "--watch") watch = argv[++i];
        else if (t == "--paths") paths = argv[++i];
        else if (t == "--dump") dump = argv[++i];
        else if (t == "--") words = true;
    }
    if (cap < 2 || cap > MAXL || a.empty() || b.empty() || (int)(a.size() + b.size()) > cap) { fprintf(stderr, "usage: see header\n"); return 2; }
    St S = parse(a, b);
    auto t0 = chrono::steady_clock::now();
    Table T(lg);
    vector<pair<string, St>> W;
    if (!watch.empty()) {
        FILE* f = fopen(watch.c_str(), "r"); char line[4096];
        while (f && fgets(line, sizeof line, f)) { string id; St s; if (parse_line(line, id, s) && s.tot() <= cap) W.push_back({id, s}); }
        if (f) fclose(f);
    }
    uint64_t triv = key(parse({1}, {2}));
    T.insert(key(S), 0);
    vector<uint64_t> fr{key(S)}, nx; bool trivial = key(S) == triv; int depth = 0;
    printf("# lcc cap=%d mode=%s start=%s\n", cap, QUOT ? "quot16" : "exact", show(S).c_str());
    while (!fr.empty() && (full || !trivial)) {
        nx.clear(); mutex mu; atomic<bool> hit{false};
        auto work = [&](int tid) {
            vector<uint64_t> loc; St t;
            for (size_t q = tid; q < fr.size(); q += threads) {
                St s = unpack(fr[q]);   // in quot mode, the canonical representative (itself a state)
                for (int m = 0; m < 14; m++) if (apply(s, m, t, cap)) {
                    uint64_t kk = key(t);
                    if (T.insert(kk, depth + 1)) { loc.push_back(kk); if (kk == triv) hit = true; }
                }
                if (loc.size() > (1 << 16)) { lock_guard<mutex> g(mu); nx.insert(nx.end(), loc.begin(), loc.end()); loc.clear(); }
            }
            lock_guard<mutex> g(mu); nx.insert(nx.end(), loc.begin(), loc.end());
        };
        vector<thread> th; for (int i = 0; i < threads; i++) th.emplace_back(work, i); for (auto& x : th) x.join();
        depth++; fr.swap(nx);
        double el = chrono::duration<double>(chrono::steady_clock::now() - t0).count();
        printf("layer %d new=%zu total=%llu t=%.1fs\n", depth, fr.size(), (unsigned long long)T.n.load(), el); fflush(stdout);
        if (T.n.load() * 10 > (T.mask + 1) * 8) { printf("ABORT table too full; raise --log2\n"); return 3; }
        if (hit) trivial = true;
    }
    printf("RESULT cap=%d mode=%s size=%llu radius=%d %s\n", cap, QUOT ? "quot16" : "exact", (unsigned long long)T.n.load(), trivial ? depth : depth - 1,
           trivial ? "TRIVIAL (standard presentation reached)" : "NOT-TRIVIAL (component exhausted, (x,y) absent)");
    // watch hits (the standard presentation is always watched as "TRIV")
    W.insert(W.begin(), {string("TRIV"), parse({1}, {2})});
    FILE* pf = paths.empty() ? nullptr : fopen(paths.c_str(), "w");
    static const int INV[14] = {0, 1, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12};
    for (auto& [id, s] : W) {
        int d = T.get(key(s));
        if (d < 0) continue;
        if (!pf) { printf("HIT %s dist=%d\n", id.c_str(), d); continue; }
        // Walk back from the actual state s along strictly decreasing BFS layers. We reach an actual state
        // u_0 with key(u_0) == key(S), i.e. u_0 = tau(S) for some tau in Sigma (tau = id in exact mode).
        vector<St> chain{s}; St cur = s, t; int cd = d; bool ok = true;
        while (cd > 0) {
            bool step = false;
            for (int m = 0; m < 14 && !step; m++) if (apply(cur, m, t, cap) && T.get(key(t)) == cd - 1) { cur = t; chain.push_back(cur); cd--; step = true; }
            if (!step) { ok = false; break; }
        }
        if (!ok) { printf("HIT %s dist=%d PATH-FAIL\n", id.c_str(), d); continue; }
        reverse(chain.begin(), chain.end());   // chain[0] = tau(S), chain.back() = s
        int tau = -1;
        for (int g = 0; g < 16 && tau < 0; g++) if (pack(sym(S, g)) == pack(chain[0])) tau = g;
        // tau^-1: find h with sym(sym(S,tau),h) == S; transport chain by h so it starts at S exactly.
        int h = -1;
        for (int g = 0; g < 16 && h < 0; g++) if (pack(sym(chain[0], g)) == pack(S)) h = g;
        vector<int> mv; St u = sym(chain[0], h);
        for (size_t i = 1; i < chain.size() && ok; i++) {
            St want = sym(chain[i], h); bool f = false;
            for (int m = 0; m < 14 && !f; m++) if (apply(u, m, t, cap) && pack(t) == pack(want)) { mv.push_back(m); u = t; f = true; }
            ok = f;
        }
        if (!ok) { printf("HIT %s dist=%d PATH-FAIL2\n", id.c_str(), d); continue; }
        // u == sigma(s) where sigma = h (as an element of Sigma, encoded 0..15)
        int sigma = h;
        printf("HIT %s dist=%d sigma=%d\n", id.c_str(), d, sigma);
        fprintf(pf, "%s sigma=%d end=%s moves=", id.c_str(), sigma, show(u).c_str());
        for (size_t i = 0; i < mv.size(); i++) fprintf(pf, "%s%d", i ? "," : "", mv[i]);
        fprintf(pf, "\n");
    }
    if (pf) fclose(pf);
    if (!dump.empty()) {
        vector<uint64_t> all; all.reserve(T.n.load());
        for (uint64_t i = 0; i <= T.mask; i++) { uint64_t v = T.k[i].load(); if (v) all.push_back(v); }
        sort(all.begin(), all.end());
        FILE* f = fopen(dump.c_str(), "wb"); fwrite(all.data(), 8, all.size(), f); fclose(f);
        printf("dumped %zu keys -> %s\n", all.size(), dump.c_str());
    }
    return trivial ? 1 : 0;
}
#endif  // LCC_NO_MAIN
